name: PR metadata annotation

on: 
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
    contents: write

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Annotate PR
        id: annotate-pr
        uses: ./
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}